name: Setup frontend project
description: Initalize frontend project for other command to be run

inputs:
  wordpress-url:
    required: true
    description: An URL where a wordpress installation can be found

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache-dependency-path: frontend/package-lock.json
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: frontend
    - name: Generate missing files
      env:
        NEXT_PUBLIC_WORDPRESS_URL: "${{ inputs.wordpress-url }}"
      shell: bash
      run: npm run prebuild
      working-directory: frontend

