name: Setup frontend project
description: Initalize frontend project for other command to be run

inputs:
  wordpress-url:
    required: false
    description: An URL where a wordpress installation can be found
  working-directory:
    required: false
    default: ./frontend
    description: A directory containing the target app

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache-dependency-path: ${{ inputs.workdir }}/package-lock.json
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.workdir }}
    - if: ${{ !!inputs.wordpress-url }}
      name: Generate missing files
      env:
        NEXT_PUBLIC_WORDPRESS_URL: "${{ inputs.wordpress-url }}"
      shell: bash
      run: npm run prebuild
      working-directory: ${{ inputs.workdir }}

