name: Deploy chromatic

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: ./.github/actions/setup-frontend-deps
      - name: Publish frontend to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
