name: Build and deploy integration

on:
    push:
        branches:
            - dev

jobs:
    deploy-wordpress:
        uses: ./.github/workflows/deploy-wordpress.yml
        secrets: inherit
        with:
            WP_DATABASE_NAME: "${{ vars.WP_DATABASE_NAME }}"
            WP_DATABASE_USER: "${{ vars.WP_DATABASE_USER }}"
            WP_DATABASE_HOST: "${{ vars.WP_DATABASE_HOST }}"
            WP_ENV: "${{ vars.WP_ENV }}"
            WEBPAGE_DOMAIN: "${{ vars.WEBPAGE_DOMAIN }}"
            WORDPRESS_DESTINATION_DIR: "${{ vars.WORDPRESS_DESTINATION_DIR }}"
            REMOTE_USERNAME: "${{ vars.REMOTE_USERNAME }}"
            REMOTE_ADDRESS: "${{ vars.REMOTE_ADDRESS }}"
            WP_DB_TABLE_PREFIX: "${{ vars.WP_DB_TABLE_PREFIX }}"
            OVPN_CONFIG_FILE: "${{ vars.OVPN_CONFIG_FILE }}"
            GH_ENVIRONMENT: Integration

    deploy-frontend:
        runs-on: ubuntu-latest
        environment: Integration
        needs:
            deploy-wordpress
        defaults:
            run:
                working-directory: ./frontend
        env:
            VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
            VERCEL_PROJECT_ID: "${{ secrets.VERCEL_PROJECT_ID }}"
            NEXT_PUBLIC_WORDPRESS_URL: "${{ vars.WEBPAGE_DOMAIN }}/${{ vars.WORDPRESS_DESTINATION_DIR }}"
        steps:
            - uses: actions/checkout@v2
            - name: "Install Vercel CLI"
              run: npm install --global vercel@latest
            - name: "Build Project Artifacts"
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: "Deploy Project Artifacts to Vercel"
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


