name: Build and deploy frontend

on:
    workflow_call:
        inputs:
            GH_ENVIRONMENT:
                required: true
                type: string
        secrets:
            OVPN_CLIENT_KEY:
                required: true
            OVPN_TLS_AUTH_KEY:
                required: true
            SSH_DEPLOY_KEY:
                required: true

concurrency:
    group: deploy-frontend-${{ inputs.GH_ENVIRONMENT }}
    cancel-in-progress: true

jobs:
    build-and-deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        environment: ${{ inputs.GH_ENVIRONMENT }}
        defaults:
            run:
                working-directory: ./frontend
        env:
            NEXT_PUBLIC_WORDPRESS_URL: "http://${{ vars.WEBPAGE_DOMAIN }}/${{ vars.WORDPRESS_DESTINATION_DIR }}"
            NEXT_BASE_PATH: "/${{ vars.WEBPAGE_DESTINATION_DIR }}"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 20
                cache-dependency-path: ./frontend/package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Build app
              run: npm run build
            - name: Upload files to the server
              uses: ./.github/actions/upload-files-to-server
              with:
                remote-filesystem-destination: "public_html/${{ vars.WEBPAGE_DESTINATION_DIR }}"
                remote-username: "${{ vars.REMOTE_USERNAME }}"
                remote-address: "${{ vars.REMOTE_ADDRESS }}"
                ovpn-config-file: "${{ vars.OVPN_CONFIG_FILE }}"
                ovpn-client-key: "${{ secrets.OVPN_CLIENT_KEY }}"
                ovpn-tls-auth-key: "${{ secrets.OVPN_TLS_AUTH_KEY }}"
                ssh-deploy-key: "${{ secrets.SSH_DEPLOY_KEY }}"
                workdir: './frontend/out'
